#!/bin/bash

rm -rf ./liteclient-build
mkdir ./liteclient-build
cd ./liteclient-build
cmake ../
cmake --build . --target lite-client
cmake --build . --target fift
cmake --build . --target func
wget  https://zababurinsv.github.io/blockchain/ton-lite-client-test1.config.json

#./lite-client/lite-client -C ton-lite-client-test1.config.json