#!/bin/bash

rm -rf ./liteclient-build-wasm
mkdir ./liteclient-build-wasm
cd ./liteclient-build-wasm
emcmake  cmake ../ \
ZLIB_LIBRARY= /home/sergey/emsdk/upstream/emscripten/cache/ports/zlib/zlib-version_1

emmake make
#cmake --build . --target lite-client
#cmake --build . --target fift
#cmake --build . --target func
#
#wget  https://zababurinsv.github.io/blockchain/ton-lite-client-test1.config.json
#
#./lite-client/lite-client -C ton-lite-client-test1.config.json